<a href="https://colab.research.google.com/github/mishad01/Data-Science-Machine-Learning/blob/main/Pattern%20Recognition/patternt_lab_2_(Naive_Bayes).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [201]:
import numpy as np
import pandas as pd

In [202]:
df = pd.read_csv("/content/drive/MyDrive/Patter Recognition Lab Dataset /Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [203]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [204]:
df['Age'][0] = np.nan

<ipython-input-204-215f1d6c5692>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Age'][0] = np.nan
<ipython-input-204-215f1d6c5692>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'][0] = np.nan

In [205]:
df.isna().sum()

User ID            0
Gender             0
Age                1
EstimatedSalary    0
Purchased          0
dtype: int64

In [206]:
#df.dropna(inplace = True) #Inplace tells to make changes in the data variable itsels

#Removes All the null values

In [207]:
#df.dropna(inplace = True)

In [208]:
df.isna().sum()

User ID            0
Gender             0
Age                1
EstimatedSalary    0
Purchased          0
dtype: int64

In [209]:
df.shape

(400, 5)

Sure! Below is a more detailed explanation of how to handle missing values using **Mean**, **Median**, and **Mode**, along with code examples in Python for each method.

---

### **1. Mean (Average)**

- **What is Mean?**
  - The **mean** is the arithmetic average of a set of numbers.
  - It is best used when data is **symmetrical** and has no **outliers**.
  - Formula:  
    \[
    \text{Mean} = \frac{\sum X}{n}
    \]
    where \( X \) is each value in the dataset and \( n \) is the number of values.

- **When to Use:**
  - For **continuous numerical data** like height, weight, temperature, etc.
  - When the data is normally distributed (i.e., symmetric, no extreme outliers).

- **Python Code Example:**

```python
import pandas as pd
import numpy as np

# Sample dataset with missing values (NaN)
data = {'Age': [25, 30, 35, np.nan, 40, np.nan, 50]}
df = pd.DataFrame(data)

# Replace missing values with the mean of the column
mean_value = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_value)

print(df)
```

---

### **2. Median**

- **What is Median?**
  - The **median** is the middle value in a dataset when it is ordered from smallest to largest.
  - If there is an **even number** of values, the median is the average of the two middle numbers.
  
- **When to Use:**
  - When the data contains **outliers** or is **skewed**.
  - The **median** is not affected by extreme values, so itâ€™s more robust than the mean in such cases.
  - Used for both **continuous and ordinal data**.

- **Python Code Example:**

```python
# Replace missing values with the median of the column
median_value = df['Age'].median()
df['Age'] = df['Age'].fillna(median_value)

print(df)
```

---

### **3. Mode**

- **What is Mode?**
  - The **mode** is the value that appears most frequently in a dataset.
  - A dataset may have **no mode**, **one mode** (unimodal), or **multiple modes** (bimodal or multimodal).
  
- **When to Use:**
  - When dealing with **categorical data** or **discrete numerical data**.
  - Especially useful for **nominal** data where there is a strong frequency of certain values.

- **Python Code Example:**

```python
# Sample dataset with categorical data
data = {'Color': ['Red', 'Blue', 'Blue', np.nan, 'Green', np.nan, 'Blue']}
df = pd.DataFrame(data)

# Replace missing values with the mode of the column
mode_value = df['Color'].mode()[0]  # mode() returns a Series, get the first value
df['Color'] = df['Color'].fillna(mode_value)

print(df)
```

---

### **Summary of When to Use Each:**

| Method  | Use Case                                           | Example                                   |
|---------|----------------------------------------------------|-------------------------------------------|
| **Mean** | Best for continuous, symmetrical data without outliers | Heights, weights, temperature            |
| **Median** | Best for skewed data or data with outliers       | Income data, house prices, test scores    |
| **Mode**   | Best for categorical data or data with high frequency values | Favorite colors, shoe sizes, most common category |

---

### **Additional Tips:**
- **Outliers and Mean**: The mean can be heavily affected by outliers (extreme values), making it less reliable when data is skewed or has large outliers.
- **Data Types**: For **numerical columns**, the **mean** and **median** are typically preferred, but for **categorical columns**, the **mode** is most suitable.
- **Mode**: In the case of categorical data with many unique values or no repeated categories, mode might not be effective.

---

Would you like more details or specific examples for other use cases or handling other types of missing data?

In [210]:
from sklearn import preprocessing

# Column to be label encoded
col_cat = ['Gender']

# Initialize the LabelEncoder
lab_encoder = preprocessing.LabelEncoder()

# Loop through the categorical columns and apply label encoding
for col in col_cat:
    df[col] = lab_encoder.fit_transform(df[col])

# Display the updated DataFrame
print(df)

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1   NaN            19000          0
1    15810944       1  35.0            20000          0
2    15668575       0  26.0            43000          0
3    15603246       0  27.0            57000          0
4    15804002       1  19.0            76000          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0            41000          1
396  15706071       1  51.0            23000          1
397  15654296       0  50.0            20000          1
398  15755018       1  36.0            33000          0
399  15594041       0  49.0            36000          1

[400 rows x 5 columns]

In [211]:
df['Gender']

0      1
1      1
2      0
3      0
4      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: Gender, Length: 400, dtype: int64

In [212]:
# Replace missing values with the median of the column
df.dropna(inplace= True)

In [213]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [214]:
from sklearn import preprocessing

# Column to be label encoded
col_cat = ['Gender']

# Initialize the LabelEncoder
lab_encoder = preprocessing.LabelEncoder()

# Loop through the categorical columns and apply label encoding
for col in col_cat:
    df[col] = lab_encoder.fit_transform(df[col])

# Display the updated DataFrame
print(df)

      User ID  Gender   Age  EstimatedSalary  Purchased
1    15810944       1  35.0            20000          0
2    15668575       0  26.0            43000          0
3    15603246       0  27.0            57000          0
4    15804002       1  19.0            76000          0
5    15728773       1  27.0            58000          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0            41000          1
396  15706071       1  51.0            23000          1
397  15654296       0  50.0            20000          1
398  15755018       1  36.0            33000          0
399  15594041       0  49.0            36000          1

[399 rows x 5 columns]

In [215]:
df['Gender']

1      1
2      0
3      0
4      1
5      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: Gender, Length: 399, dtype: int64

In [216]:
df

      User ID  Gender   Age  EstimatedSalary  Purchased
1    15810944       1  35.0            20000          0
2    15668575       0  26.0            43000          0
3    15603246       0  27.0            57000          0
4    15804002       1  19.0            76000          0
5    15728773       1  27.0            58000          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0            41000          1
396  15706071       1  51.0            23000          1
397  15654296       0  50.0            20000          1
398  15755018       1  36.0            33000          0
399  15594041       0  49.0            36000          1

[399 rows x 5 columns]

In [217]:
y = df['Purchased'].values
X = df.iloc[:,1:4].values
#y = df.iloc[:,-1]
#X = X.astype(int)

In [218]:
X

array([[1.0e+00, 3.5e+01, 2.0e+04],
       [0.0e+00, 2.6e+01, 4.3e+04],
       [0.0e+00, 2.7e+01, 5.7e+04],
       ...,
       [0.0e+00, 5.0e+01, 2.0e+04],
       [1.0e+00, 3.6e+01, 3.3e+04],
       [0.0e+00, 4.9e+01, 3.6e+04]])

In [219]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [220]:
X_train.shape

(319, 3)

In [221]:
X_test.shape

(80, 3)

In [222]:
y_train.shape

(319,)

In [223]:
y_test.shape

(80,)

#Feature Scaling

In [224]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()  # Create a StandardScaler instance

X_train = sc.fit_transform(X_train)  # Fit the scaler on the training data and transform it
X_test = sc.transform(X_test)  # Use the same scaler to transform the test data (without fitting)

In [225]:
X_test[:3]

array([[-1.00313973, -1.63046804, -0.04319551],
       [-1.00313973,  0.35724905,  0.01594341],
       [-1.00313973, -0.21067012, -0.45716793]])

#Model Training

In [226]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [239]:
y_pred = classifier.predict(X_test)

In [240]:
y_pred,y_test

(array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1]))

#Generating performance metrics

In [241]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[53  4]
 [ 4 19]]

In [242]:
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

Precision: 0.8260869565217391

In [236]:
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.8260869565217391

In [237]:
f1 = f1_score(y_test, y_pred)
print(f1)

0.8260869565217391